const BLOCKED_SHELL_SYNTAX = [/&&/, /\|\|/, /;/, /\|/, /(^|[^<])>(?!>)/, />>/, /</, /\$\(/, /`/];
const DESTRUCTIVE_COMMAND_PATTERNS = [
	/\brm\b/i,
	/\brmdir\b/i,
	/\bmv\b/i,
	/\bcp\b/i,
	/\bmkdir\b/i,
	/\btouch\b/i,
	/\bchmod\b/i,
	/\bchown\b/i,
	/\bchgrp\b/i,
	/\bln\b/i,
	/\btee\b/i,
	/\btruncate\b/i,
	/\bdd\b/i,
	/\bshred\b/i,
	/\bnpm\s+(install|uninstall|update|ci|link|publish)\b/i,
	/\byarn\s+(add|remove|install|publish)\b/i,
	/\bpnpm\s+(add|remove|install|publish)\b/i,
	/\bbun\s+(add|remove|install|update)\b/i,
	/\buv\s+(add|remove|sync|pip|venv)\b/i,
	/\bpip\s+(install|uninstall)\b/i,
	/\bapt(-get)?\s+(install|remove|purge|update|upgrade)\b/i,
	/\bbrew\s+(install|uninstall|upgrade)\b/i,
	/\bgit\s+(add|commit|push|pull|merge|rebase|reset|checkout|switch|restore|stash|cherry-pick|revert|tag|init|clone)\b/i,
	/\bsudo\b/i,
	/\bsu\b/i,
	/\bkill(all)?\b/i,
	/\bpkill\b/i,
	/\breboot\b/i,
	/\bshutdown\b/i,
	/\bsystemctl\s+(start|stop|restart|enable|disable)\b/i,
	/\bservice\s+\S+\s+(start|stop|restart)\b/i,
	/\b(vim?|nano|emacs|code|subl)\b/i,
];
const SAFE_COMMAND_PATTERNS = [
	/^\s*pwd\b/i,
	/^\s*ls\b/i,
	/^\s*tree\b/i,
	/^\s*cat\b/i,
	/^\s*head\b/i,
	/^\s*tail\b/i,
	/^\s*less\b/i,
	/^\s*more\b/i,
	/^\s*wc\b/i,
	/^\s*sort\b/i,
	/^\s*uniq\b/i,
	/^\s*diff\b/i,
	/^\s*file\b/i,
	/^\s*stat\b/i,
	/^\s*du\b/i,
	/^\s*df\b/i,
	/^\s*which\b/i,
	/^\s*whereis\b/i,
	/^\s*type\b/i,
	/^\s*env\b/i,
	/^\s*printenv\b/i,
	/^\s*uname\b/i,
	/^\s*whoami\b/i,
	/^\s*id\b/i,
	/^\s*date\b/i,
	/^\s*uptime\b/i,
	/^\s*ps\b/i,
	/^\s*top\b/i,
	/^\s*htop\b/i,
	/^\s*free\b/i,
	/^\s*grep\b/i,
	/^\s*find\b/i,
	/^\s*rg\b/i,
	/^\s*fd\b/i,
	/^\s*jq\b/i,
	/^\s*sed\s+-n\b/i,
	/^\s*awk\b/i,
	/^\s*git\s+(status|log|diff|show)\b/i,
	/^\s*git\s+branch(\s+--list(\s+\S+)*)?\s*$/i,
	/^\s*git\s+config\s+--get\b/i,
	/^\s*git\s+ls-/i,
	/^\s*bun\s+--version\b/i,
	/^\s*bun\s+why\b/i,
	/^\s*bun\s+outdated\b/i,
	/^\s*npm\s+(list|ls|view|info|search|outdated|audit)\b/i,
	/^\s*yarn\s+(list|info|why|audit)\b/i,
	/^\s*uv\s+tree\b/i,
	/^\s*node\s+--version\b/i,
	/^\s*python\s+--version\b/i,
	/^\s*bat\b/i,
	/^\s*exa\b/i,
];

export function isSafeBashCommand(command: string): boolean {
	const trimmed = command.trim();
	if (!trimmed) return false;
	if (BLOCKED_SHELL_SYNTAX.some((pattern) => pattern.test(trimmed))) return false;
	if (DESTRUCTIVE_COMMAND_PATTERNS.some((pattern) => pattern.test(trimmed))) return false;
	return SAFE_COMMAND_PATTERNS.some((pattern) => pattern.test(trimmed));
}
